server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        # Ruta para Autenticación 
        - id: ms-autenticacion
          uri: http://localhost:8081
          predicates:
            - Path=/api/auth/**

        # Ruta para Dueños 
        - id: ms-duenos
          uri: http://localhost:8082
          predicates:
            - Path=/api/duenos/**

        # Ruta para Mascotas 
        - id: ms-mascotas
          uri: http://localhost:8083
          predicates:
            - Path=/api/mascotas/**