server:
    port: 9091

spring:
    application:
        name: api-gateway-vetnova

    cloud:
        gateway:
            routes:
                - id: ms-autenticacion
                  uri: http://localhost:8081
                  predicates:
                      - Path=/api/auth,/api/auth/**

                - id: ms-duenos
                  uri: http://localhost:8082
                  predicates:
                      - Path=/api/duenos,/api/duenos/**

                - id: ms-mascotas
                  uri: http://localhost:8083
                  predicates:
                      - Path=/api/mascotas,/api/mascotas/**

                - id: ms-documento
                  uri: http://localhost:8084
                  predicates:
                      - Path=/api/v1/documentos,/api/v1/documentos/**

                - id: ms-ficha
                  uri: http://localhost:8085
                  predicates:
                      - Path=/api/v1/fichas,/api/v1/fichas/**

                - id: ms-agenda
                  uri: http://localhost:8086
                  predicates:
                      - Path=/api/v1/citas,/api/v1/citas/**

                - id: ms-inventario
                  uri: http://localhost:8087
                  predicates:
                      - Path=/productos,/productos/**

                - id: ms-logistica-proveedores
                  uri: http://localhost:8088
                  predicates:
                      - Path=/proveedores,/proveedores/**

                - id: ms-logistica-solicitudes
                  uri: http://localhost:8088
                  predicates:
                      - Path=/solicitudes-reposicion,/solicitudes-reposicion/**

                - id: ms-ecommerce
                  uri: http://localhost:8089
                  predicates:
                      - Path=/productos-web,/productos-web/**

                - id: ms-facturacion
                  uri: http://localhost:9090
                  predicates:
                      - Path=/facturas,/facturas/**